language: python
python:
 - "2.7"

before_install:
# Workaround for a permissions issue with Travis virtual machine images
# that breaks Python's multiprocessing:
# https://github.com/travis-ci/travis-cookbooks/issues/155
 - sudo rm -rf /dev/shm
 - sudo ln -s /run/shm /dev/shm
 - sudo apt-get update
 - sudo apt-get install ufraw-batch python-opencv libhdf5-serial-dev libnetcdf-dev libatlas-base-dev gfortran
 - ln -s /usr/share/pyshared/cv.py /usr/lib/pyshared/python2.7/cv2.so $VIRTUAL_ENV/lib/python2.7/site-packages/
 - pip install -q nose coverage
 - pip install -q coveralls six
 - pip install -q numpy
 - pip install -q scipy
 - pip install -q matplotlib
 - pip install -q git+https://github.com/scikit-image/scikit-image.git

install:
 - ./install

script:
 - ./run_tests
# Eventually, we want to remove --exit-zero below, and only pass tests if no
# flake8 errors exist
 - flake8 --exit-zero tests timestream

after_script:
 - coveralls
